### ISSUE TITLE
还不如直接写bat和bash

### ISSUE THREAD

**Issue by hanxi** [xiyoo0812/lplantuml#1]
看了下实现，就是遍历目录然后调用 java 命令。所以没必要引入 lua

**Comment by hanxi** [comment]
相关知识点

- bat 如何遍历目录
- bat 如何接收参数
- bash 如何遍历目录
- bash 如何接收参数

**Comment by xiyoo0812** [comment]
哈哈，从一个开源库拔过来的，他的代码很复杂，改造之后就这点内容，改完发现核心就是bash
